name: Cypress on Chrome

on: [push]
jobs:
   chrome:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Cypress run
           uses: cypress-io/github-action@v4   
           
   
