name: CypressDemo

on: push

jobs:
  chrome:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RunOnChrome
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/frame.cy.js
      
