name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/frame.cy.js
          wait-on-timeout: 180
              
