name: CypressOnChrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RunOnChrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          spec: cypress/e2e/frame.cy.js
          record: true
          parallel: true
          timeout-minutes: 10
          browser: chrome
